[package]
name = "montador_ijvm"
version = "0.1.0"
authors = ["Jo√£o Luiz Albuquerque <joaoalbuquerque@great.ufc.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
